logging:
  level:
    io.mustelidae.grantotter: info
    org.springframework.boot.actuate: off
    org.springframework.web: debug
    org.springframework.boot: info
    io.swagger.models.parameters.AbstractSerializableParameter: error
    org.mongodb.driver: info
    io.mustelidae.grantotter.config.RequestResponseLogFilter: debug

server:
  error:
    include-stacktrace: always
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  port: 6200

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        use_sql_comments: true
        default_batch_fetch_size: 50
        enable_lazy_load_no_trans: true
        format_sql: true
        dialect:
          storage_engine: innodb
  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 3
      maximum-pool-size: 30
      pool-name: SpirngBootHikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:6201/local?serverTimezone=Asia/Seoul
    username: local
    password: local
springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    tagsSorter: alpha
  cache:
    disabled: true

app:
  spec:
    connection-timeout: 1000
    response-timeout: 1000
    logging: true
    use-dummy: false
