package io.mustelidae.grantotter.domain.client

import java.net.URI

class SpecDummyClient : SpecClient {
    override fun hasSpec(uri: URI): Boolean {
        return true
    }

    override fun getSpec(uri: URI, headers: Map<String, Any>?): String {
        return """
            {
               "openapi":"3.0.1",
               "info":{
                  "title":"OpenAPI definition",
                  "version":"v0"
               },
               "servers":[
                  {
                     "url":"http://localhost:6200",
                     "description":"Generated server url"
                  }
               ],
               "tags":[
                  {
                     "name":"Management",
                     "description":"API Docket Spec Management"
                  }
               ],
               "paths":{
                  "/crawling/manual":{
                     "put":{
                        "tags":[
                           "crawling-controller"
                        ],
                        "description":"retry crawling all",
                        "operationId":"crawlingAll",
                        "responses":{
                           "400":{
                              "description":"Bad Request",
                              "content":{
                                 "*/*":{
                                    "schema":{
                                       "ref":"#/components/schemas/GrantOtter.Error"
                                    }
                                 }
                              }
                           },
                           "500":{
                              "description":"Internal Server Error",
                              "content":{
                                 "*/*":{
                                    "schema":{
                                       "ref":"#/components/schemas/GrantOtter.Error"
                                    }
                                 }
                              }
                           },
                           "200":{
                              "description":"OK",
                              "content":{
                                 "*/*":{
                                    "schema":{
                                       "ref":"#/components/schemas/GrantOtter.Reply"
                                    }
                                 }
                              }
                           }
                        }
                     }
                  },
                  "/swagger/specifications":{
                     "get":{
                        "tags":[
                           "Management"
                        ],
                        "operationId":"findAll",
                        "responses":{
                           "400":{
                              "description":"Bad Request",
                              "content":{
                                 "*/*":{
                                    "schema":{
                                       "ref":"#/components/schemas/GrantOtter.Error"
                                    }
                                 }
                              }
                           },
                           "500":{
                              "description":"Internal Server Error",
                              "content":{
                                 "*/*":{
                                    "schema":{
                                       "ref":"#/components/schemas/GrantOtter.Error"
                                    }
                                 }
                              }
                           },
                           "200":{
                              "description":"OK",
                              "content":{
                                 "*/*":{
                                    "schema":{
                                       "ref":"#/components/schemas/GrantOtter.Replies"
                                    }
                                 }
                              }
                           }
                        }
                     },
                     "post":{
                        "tags":[
                           "Management"
                        ],
                        "operationId":"add",
                        "requestBody":{
                           "content":{
                              "application/json":{
                                 "schema":{
                                    "ref":"#/components/schemas/GrantOtter.SwaggerSpec.Request"
                                 }
                              }
                           },
                           "required":true
                        },
                        "responses":{
                           "400":{
                              "description":"Bad Request",
                              "content":{
                                 "*/*":{
                                    "schema":{
                                       "ref":"#/components/schemas/GrantOtter.Error"
                                    }
                                 }
                              }
                           },
                           "500":{
                              "description":"Internal Server Error",
                              "content":{
                                 "*/*":{
                                    "schema":{
                                       "ref":"#/components/schemas/GrantOtter.Error"
                                    }
                                 }
                              }
                           },
                           "201":{
                              "description":"Created",
                              "content":{
                                 "*/*":{
                                    "schema":{
                                       "ref":"#/components/schemas/GrantOtter.Reply"
                                    }
                                 }
                              }
                           }
                        }
                     }
                  },
                  "/swagger/specifications/{id}":{
                     "get":{
                        "tags":[
                           "Management"
                        ],
                        "operationId":"findOne",
                        "parameters":[
                           {
                              "name":"id",
                              "in":"path",
                              "required":true,
                              "schema":{
                                 "type":"string"
                              }
                           }
                        ],
                        "responses":{
                           "400":{
                              "description":"Bad Request",
                              "content":{
                                 "*/*":{
                                    "schema":{
                                       "ref":"#/components/schemas/GrantOtter.Error"
                                    }
                                 }
                              }
                           },
                           "500":{
                              "description":"Internal Server Error",
                              "content":{
                                 "*/*":{
                                    "schema":{
                                       "ref":"#/components/schemas/GrantOtter.Error"
                                    }
                                 }
                              }
                           },
                           "200":{
                              "description":"OK",
                              "content":{
                                 "*/*":{
                                    "schema":{
                                       "ref":"#/components/schemas/GrantOtter.Reply"
                                    }
                                 }
                              }
                           }
                        }
                     },
                     "delete":{
                        "tags":[
                           "Management"
                        ],
                        "operationId":"remove",
                        "parameters":[
                           {
                              "name":"id",
                              "in":"path",
                              "required":true,
                              "schema":{
                                 "type":"string"
                              }
                           }
                        ],
                        "responses":{
                           "400":{
                              "description":"Bad Request",
                              "content":{
                                 "*/*":{
                                    "schema":{
                                       "ref":"#/components/schemas/GrantOtter.Error"
                                    }
                                 }
                              }
                           },
                           "500":{
                              "description":"Internal Server Error",
                              "content":{
                                 "*/*":{
                                    "schema":{
                                       "ref":"#/components/schemas/GrantOtter.Error"
                                    }
                                 }
                              }
                           },
                           "200":{
                              "description":"OK",
                              "content":{
                                 "*/*":{
                                    "schema":{
                                       "ref":"#/components/schemas/GrantOtter.Reply"
                                    }
                                 }
                              }
                           }
                        }
                     }
                  }
               },
               "components":{
                  "schemas":{
                     "GrantOtter.Error":{
                        "required":[
                           "code",
                           "message",
                           "timestamp",
                           "type"
                        ],
                        "type":"object",
                        "properties":{
                           "timestamp":{
                              "type":"string"
                           },
                           "code":{
                              "type":"string"
                           },
                           "description":{
                              "type":"string"
                           },
                           "message":{
                              "type":"string"
                           },
                           "type":{
                              "type":"string"
                           },
                           "refCode":{
                              "type":"string"
                           },
                           "trace":{
                              "type":"string"
                           }
                        },
                        "description":"API ������ ������ ������"
                     },
                     "GrantOtter.Reply":{
                        "type":"object",
                        "description":"Http Json Response Base Format (Class ��������� ������������ ��������� ��� ������)"
                     },
                     "GrantOtter.SwaggerSpec.Request":{
                        "required":[
                           "group",
                           "name",
                           "type",
                           "url",
                           "version"
                        ],
                        "type":"object",
                        "properties":{
                           "type":{
                              "type":"string",
                              "enum":[
                                 "JSON",
                                 "YAML"
                              ]
                           },
                           "group":{
                              "type":"string"
                           },
                           "name":{
                              "type":"string"
                           },
                           "url":{
                              "type":"string"
                           },
                           "version":{
                              "type":"string"
                           },
                           "description":{
                              "type":"string"
                           },
                           "headers":{
                              "type":"object",
                              "additionalProperties":{
                                 "type":"object"
                              }
                           },
                           "tags":{
                              "type":"array",
                              "items":{
                                 "type":"string"
                              }
                           }
                        }
                     },
                     "GrantOtter.Replies":{
                        "required":[
                           "content"
                        ],
                        "type":"object",
                        "properties":{
                           "content":{
                              "type":"array",
                              "items":{
                                 "ref":"#/components/schemas/GrantOtter.SwaggerSpec.Reply"
                              }
                           }
                        },
                        "description":"Http Json Response Base Format (Collection ��������� ������������ ��������� ��� ������)"
                     },
                     "GrantOtter.SwaggerSpec.Reply":{
                        "required":[
                           "createdAt",
                           "id",
                           "name",
                           "type",
                           "url",
                           "version"
                        ],
                        "type":"object",
                        "properties":{
                           "id":{
                              "type":"string"
                           },
                           "createdAt":{
                              "type":"object",
                              "example":"2024-02-06T13:28:05.050676"
                           },
                           "name":{
                              "type":"string"
                           },
                           "type":{
                              "type":"string",
                              "enum":[
                                 "JSON",
                                 "YAML"
                              ]
                           },
                           "url":{
                              "type":"string"
                           },
                           "version":{
                              "type":"string"
                           },
                           "description":{
                              "type":"string"
                           },
                           "headers":{
                              "type":"object",
                              "additionalProperties":{
                                 "type":"object"
                              }
                           },
                           "tags":{
                              "type":"array",
                              "items":{
                                 "type":"string"
                              }
                           }
                        }
                     }
                  }
               }
            }
        """.trimIndent()
    }
}
